radios:
- channels: 1
  support_p2p_device: true
  use_chanctx: false
  destroy_radio_on_close: true
  radio_name: "link1_node1"
  no_vif: false
  perm_addr:
  - 0x66
  - 0x0
  - 0x0
  - 0x0
  - 0x1
  - 0x0
- channels: 1
  support_p2p_device: true
  use_chanctx: false
  destroy_radio_on_close: true
  radio_name: "link1_node2"
  no_vif: false
  perm_addr:
  - 0x66
  - 0x0
  - 0x0
  - 0x0
  - 0x2
  - 0x0